// Strings for the /newui account / master-login panel. Kept as a small
// self-contained table (not folded into the big i18n STRINGS yet) so the
// account feature stays isolated while it is prototyped -- move into i18n.js
// once the design lands. Language comes from the same source as the rest of
// the chrome (i18n getLang(), backed by localStorage 'mudjs.lang').
import { getLang } from './i18n';

const STRINGS = {
  en: {
    new_hero_lead: 'New to Dreamland?',
    new_hero_body: 'Type the name of your future game character in the terminal window to get started. Yep, this is a typing game, get used to it.',
    create_char: 'Create character',
    cr_title: 'Create your hero',
    cr_pass2: 'Repeat password',
    cr_pw_hint: 'At least 5 characters.',
    cr_sr: 'Screen-reader support (for blind players)',
    cr_create: 'Create hero',
    cr_creating: 'Creating your hero…',
    cr_fix_name: 'Pick an available name first.',
    cr_pw_short: 'Password must be at least 5 characters.',
    cr_pw_mismatch: "The passwords don't match.",
    cr_taken_race: 'That name was just taken. Pick another.',
    cr_unavailable: 'Web creation is off right now — use the terminal.',
    nm_checking: 'Checking…',
    nm_ok: 'Available',
    nm_taken: 'Taken — pick another',
    nm_reserved: "That name can't be used",
    nm_online: 'Someone is online under that name',
    nm_bad: 'Letters only, no spaces or digits',
    pathA: 'Log in with your character',
    name: 'Character name',
    password: 'Character password',
    enter: 'Enter',
    pathB: 'Log in with your account',
    via_email: 'E-mail',
    via_discord: 'Discord',
    via_telegram: 'Telegram',
    roster: 'Choose your hero',
    roster_lead: 'Available characters on your {title} account',
    entering: 'Entering…',
    authenticating: 'Authenticating…',
    email_ph: 'your e-mail',
    code_ph: '6-digit code',
    send_code: 'Send code',
    verify: 'Verify',
    sending: 'Sending…',
    sent_hint: 'We mailed you a code. Enter it below.',
    rate: 'Too many requests. Try again later.',
    badcode: 'Wrong or expired code',
    nolink: "This e-mail isn't linked to any character yet. Link it in the game with the account command.",
    notowned: "That character isn't on this account.",
    enterfail: 'Could not enter. Try again.',
    expired: 'Session expired. Log in again.',
    berror: 'Something went wrong. Try again.',
    soon: 'Coming soon. Use e-mail or your character for now.',
    fail: 'Check your name or password',
    lang: 'Language',
    back: 'Back',
    logout: 'Log out',
    loggingout: 'Logging out…',
    loading: 'Checking your account…',
    tg_head: 'Log in with Telegram',
    tg_hint: 'Tap the Telegram button and confirm in the app. Your Telegram must already be linked to a character in the game.',
    tg_nolink: "This Telegram account isn't linked to any character yet. Link it in the game with the account command.",
    d_nolink: "This Discord account isn't linked to any character yet. Link it in the game with the account command.",
  },
  ru: {
    new_hero_lead: 'Впервые в Dreamland?',
    new_hero_body: 'Напечатай имя своего будущего персонажа в окне терминала, и вперёд. Да, это игра про печатание. Привыкай.',
    create_char: 'Создать персонажа',
    cr_title: 'Создай своего героя',
    cr_pass2: 'Повтори пароль',
    cr_pw_hint: 'Не короче пяти символов.',
    cr_sr: 'Поддержка скринридера (для незрячих)',
    cr_create: 'Создать героя',
    cr_creating: 'Создаём героя…',
    cr_fix_name: 'Сначала выбери свободное имя.',
    cr_pw_short: 'Пароль должен быть не короче пяти символов.',
    cr_pw_mismatch: 'Пароли не совпадают.',
    cr_taken_race: 'Имя только что заняли. Выбери другое.',
    cr_unavailable: 'Создание через веб сейчас выключено — играй через терминал.',
    nm_checking: 'Проверяю…',
    nm_ok: 'Свободно',
    nm_taken: 'Занято — выбери другое',
    nm_reserved: 'Это имя нельзя использовать',
    nm_online: 'Кто-то уже в игре под этим именем',
    nm_bad: 'Только буквы, без пробелов и цифр',
    pathA: 'Войти своим персонажем',
    name: 'Имя персонажа',
    password: 'Пароль персонажа',
    enter: 'Войти',
    pathB: 'Войти аккаунтом',
    via_email: 'E-mail',
    via_discord: 'Discord',
    via_telegram: 'Telegram',
    roster: 'Выбери героя',
    roster_lead: 'Доступные персонажи на аккаунте {title}',
    entering: 'Вход…',
    authenticating: 'Аутентификация…',
    email_ph: 'твоя почта',
    code_ph: '6-значный код',
    send_code: 'Отправить код',
    verify: 'Проверить',
    sending: 'Отправка…',
    sent_hint: 'Мы отправили код на почту. Введи его ниже.',
    rate: 'Слишком много запросов. Попробуй позже.',
    badcode: 'Неверный или просроченный код',
    nolink: 'Эта почта ещё не привязана к персонажу. Привяжи её в игре командой аккаунт.',
    notowned: 'Этот персонаж не на этом аккаунте.',
    enterfail: 'Не удалось войти. Попробуй ещё раз.',
    expired: 'Сессия истекла. Войди заново.',
    berror: 'Что-то пошло не так. Попробуй ещё раз.',
    soon: 'Скоро. Пока войди почтой или персонажем.',
    fail: 'Проверь имя или пароль',
    lang: 'Язык',
    back: 'Назад',
    logout: 'Выйти',
    loggingout: 'Выходим…',
    loading: 'Проверяем аккаунт…',
    tg_head: 'Войти через Telegram',
    tg_hint: 'Нажми кнопку Telegram и подтверди в приложении. Твой Telegram должен быть уже привязан к персонажу в игре.',
    tg_nolink: 'Этот Telegram ещё не привязан к персонажу. Привяжи его в игре командой аккаунт.',
    d_nolink: 'Этот Discord ещё не привязан к персонажу. Привяжи его в игре командой аккаунт.',
  },
  ua: {
    new_hero_lead: 'Вперше у Dreamland?',
    new_hero_body: 'Надрукуй імʼя свого майбутнього персонажа у вікні термінала, і погнали. Так, це гра про друкування. Звикай.',
    create_char: 'Створити персонажа',
    cr_title: 'Створи свого героя',
    cr_pass2: 'Повтори пароль',
    cr_pw_hint: 'Не коротший за пʼять символів.',
    cr_sr: 'Підтримка скринрідера (для незрячих)',
    cr_create: 'Створити героя',
    cr_creating: 'Створюємо героя…',
    cr_fix_name: 'Спершу вибери вільне імʼя.',
    cr_pw_short: 'Пароль має бути не коротшим за пʼять символів.',
    cr_pw_mismatch: 'Паролі не збігаються.',
    cr_taken_race: 'Імʼя щойно зайняли. Вибери інше.',
    cr_unavailable: 'Створення через веб зараз вимкнено — грай через термінал.',
    nm_checking: 'Перевіряю…',
    nm_ok: 'Вільне',
    nm_taken: 'Зайнято — вибери інше',
    nm_reserved: 'Це імʼя не можна використати',
    nm_online: 'Хтось уже в грі під цим імʼям',
    nm_bad: 'Лише літери, без пробілів і цифр',
    pathA: 'Увійти своїм персонажем',
    name: 'Імʼя персонажа',
    password: 'Пароль персонажа',
    enter: 'Увійти',
    pathB: 'Увійти акаунтом',
    via_email: 'E-mail',
    via_discord: 'Discord',
    via_telegram: 'Telegram',
    roster: 'Обери героя',
    roster_lead: 'Доступні персонажі на акаунті {title}',
    entering: 'Вхід…',
    authenticating: 'Автентифікація…',
    email_ph: 'твоя пошта',
    code_ph: '6-значний код',
    send_code: 'Надіслати код',
    verify: 'Перевірити',
    sending: 'Надсилаю…',
    sent_hint: 'Код надіслано на пошту. Введи його нижче.',
    rate: 'Забагато спроб. Спробуй пізніше.',
    badcode: 'Невірний або прострочений код',
    nolink: 'Ця пошта ще не привʼязана до персонажа. Привʼяжи її у грі командою акаунт.',
    notowned: 'Цей герой не на цьому акаунті.',
    enterfail: 'Не вдалося увійти. Спробуй ще раз.',
    expired: 'Сесія завершилась. Увійди знову.',
    berror: 'Щось пішло не так. Спробуй ще раз.',
    soon: 'Скоро. Поки увійди поштою або персонажем.',
    fail: 'Перевір імʼя або пароль',
    lang: 'Мова',
    back: 'Назад',
    logout: 'Вийти',
    loggingout: 'Виходимо…',
    loading: 'Перевіряємо акаунт…',
    tg_head: 'Увійти через Telegram',
    tg_hint: 'Натисни кнопку Telegram і підтверди в застосунку. Твій Telegram має бути вже привʼязаний до персонажа у грі.',
    tg_nolink: 'Цей Telegram ще не привʼязаний до персонажа. Привʼяжи його у грі командою акаунт.',
    d_nolink: 'Цей Discord ще не привʼязаний до персонажа. Привʼяжи його у грі командою акаунт.',
  },
};

// at(key, lang?) -- account-panel string, defaulting to the current UI language,
// falling back to English then to the key (same contract as i18n t()).
export function at(key, lang) {
  const l = lang || getLang();
  const table = STRINGS[l] || STRINGS.en;
  if (table[key] != null) return table[key];
  if (STRINGS.en[key] != null) return STRINGS.en[key];
  return key;
}

export const LANGS = [
  { code: 'en', label: 'English' },
  { code: 'ua', label: 'Українська' },
  { code: 'ru', label: 'Русский' },
];
